######################################################
#                                                    #
#               Stalwart IMAP config                 #
#                                                    #
######################################################

bind-addr: 0.0.0.0
bind-port: 143
bind-port-tls: 993
log-level: info

jmap-url: https://localhost:8080
#jmap-trusted-hosts: jmap1.example.org;jmap2.example.org


# ----------------------------------------
#  IMAP-to-JMAP Id Cache configuration
# ----------------------------------------

cache-dir: /usr/local/stalwart-imap/data
cache-purge-every: 0 3 *
cache-removed-id-ttl: 2592000 # secs

# ----------------------------------------
#  TLS certificates
# ----------------------------------------

cert-path: /usr/local/stalwart-imap/etc/imap.crt
key-path: /usr/local/stalwart-imap/etc/imap.key

# ----------------------------------------
#  Default folder names
# ----------------------------------------
name-shared: Shared Folders
name-all: All Mail

# ----------------------------------------
#  Limits
# ----------------------------------------

max-request-size: 52428800
#worker-pool-size: 8
